# ExtractIconNames.ps1
# Extracts all icon base names from wwwroot/gfx directories and generates IconNames.cs

param(
    [string]$WwwrootPath = "..\..\HnHMapperServer.Web\wwwroot",
    [string]$OutputPath = "..\Constants\IconNames.cs"
)

Write-Host "Extracting icon names from: $WwwrootPath" -ForegroundColor Cyan

# Find all PNG files in gfx directory
$gfxPath = Join-Path $WwwrootPath "gfx"
if (-not (Test-Path $gfxPath)) {
    Write-Error "Path not found: $gfxPath"
    exit 1
}

Write-Host "Scanning for PNG files..." -ForegroundColor Yellow
$pngFiles = Get-ChildItem -Path $gfxPath -Recurse -Filter "*.png"
Write-Host "Found $($pngFiles.Count) PNG files" -ForegroundColor Green

# Extract base names (remove .png extension)
$baseNames = $pngFiles | ForEach-Object {
    $_.BaseName
} | Sort-Object -Unique

Write-Host "Unique base names: $($baseNames.Count)" -ForegroundColor Green

# Generate C# class
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$classContent = @"
// Auto-generated by ExtractIconNames.ps1
// Generated: $timestamp
// Total icons: $($baseNames.Count)

namespace HnHMapperServer.Core.Constants;

/// <summary>
/// Contains all icon base names extracted from wwwroot/gfx directories.
/// Used for generating memorable tenant and map names.
/// </summary>
public static class IconNames
{
    /// <summary>
    /// Array of all unique icon base names (without path or .png extension).
    /// Total count: $($baseNames.Count)
    /// </summary>
    public static readonly string[] Names = new[]
    {
"@

# Add icon names (4 per line for readability)
$lines = @()
for ($i = 0; $i -lt $baseNames.Count; $i += 4) {
    $chunk = $baseNames[$i..([Math]::Min($i + 3, $baseNames.Count - 1))]
    $quotedChunk = $chunk | ForEach-Object { "`"$_`"" }
    $line = "        " + ($quotedChunk -join ", ")
    if ($i + 4 -lt $baseNames.Count) {
        $line += ","
    }
    $lines += $line
}

$classContent += ($lines -join "`n")
$classContent += @"

    };

    /// <summary>
    /// Gets a random icon name from the collection.
    /// </summary>
    public static string GetRandom()
    {
        return Names[Random.Shared.Next(Names.Length)];
    }
}
"@

# Write to output file
$outputFullPath = Join-Path (Get-Location) $OutputPath
$outputDir = Split-Path $outputFullPath -Parent
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$classContent | Out-File -FilePath $outputFullPath -Encoding UTF8 -Force
Write-Host "Generated: $outputFullPath" -ForegroundColor Green
Write-Host "Class contains $($baseNames.Count) icon names" -ForegroundColor Cyan

# Show sample names
Write-Host "`nSample icon names:" -ForegroundColor Yellow
$baseNames | Select-Object -First 10 | ForEach-Object { Write-Host "  - $_" }
Write-Host "  ..." -ForegroundColor DarkGray

Write-Host "`nDone! IconNames.cs has been generated." -ForegroundColor Green
